// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB15mpyYdreVBkh9C84oG2XCFjvEyoa3aU',
    appId: '1:427882411809:web:d0a45e0ca0ed5140bf7060',
    messagingSenderId: '427882411809',
    projectId: 'careplus-1c9a7',
    authDomain: 'careplus-1c9a7.firebaseapp.com',
    storageBucket: 'careplus-1c9a7.firebasestorage.app',
    measurementId: 'G-Z7MLL89SYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnroJuaVe2ECKF749hTiIsas_IPK9aGgk',
    appId: '1:427882411809:android:143e79bd0fe9d8cbbf7060',
    messagingSenderId: '427882411809',
    projectId: 'careplus-1c9a7',
    storageBucket: 'careplus-1c9a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwCb6w7bIi00nXjs9NHIZAejTCvZYUpE',
    appId: '1:427882411809:ios:987591f8100b05e8bf7060',
    messagingSenderId: '427882411809',
    projectId: 'careplus-1c9a7',
    storageBucket: 'careplus-1c9a7.firebasestorage.app',
    iosBundleId: 'com.example.carepulse',
  );
}
